@baseUrl = http://localhost:8080

### Post - all
GET {{baseUrl}}/posts

### Post - add
POST {{baseUrl}}/posts/3
Content-Type:application/json

{
  "title": "newtitle",
  "content": "newcontent"
}

### Post - get one
GET {{baseUrl}}/posts/2


### post - update
PUT {{baseUrl}}/posts/1
Content-Type: application/json

{
  "title": "updatetitle",
  "content": "updatecontent"
}

### post -delete
DELETE {{baseUrl}}/posts/1

### user - all
GET {{baseUrl}}/users

### user - add
POST {{baseUrl}}/users
Content-Type:application/json

{
  "name": "youmin",
  "email": "abc@gmail.com",
  "mobile": "010-1111-1111"
}

> {%
    client.global.set("newerId",response.body.id);
%}

### user - get one
GET {{baseUrl}}/users/{{newerId}}

### user - update
PUT {{baseUrl}}/users/6
Content-Type: application/json

{
  "name": "youmin",
  "mobile": "010-2222-3333"
}

### user -delete
DELETE {{baseUrl}}/users/1

### user -get 1
GET {{baseUrl}}/users/1

### hello
GET {{baseUrl}}/hello

### hi
GET {{baseUrl}}/hi?name=youmin

> {%
    client.global.set("greeting",response.body);
 %}

### hi/{name}

GET {{baseUrl}}/hi/{{greeting}}
